config/routes.rb
Rails.application.routes.draw do

  resources :runs do
    resources :comments
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}

  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only:[:index]

  root "top#index"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :run
  has_many :notifications, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.build(comment_params)
    @run = @comment.run
    @notification = @comment.notifications.build(user_id: @run.user.id )

    respond_to do |format|
      if @comment.save
        format.html { redirect_to run_path(@run), notice: 'コメントを投稿しました。' }
        format.js { render :index}
        unless @comment.run.user_id == current_user.id
          Pusher.trigger("user_#{@comment.run.user_id}_channel", 'comment_created', {
            message: 'あなたが投稿した記録にコメントが付きました'
          })
        end
        Pusher.trigger("user_#{@comment.run.user_id}_channel", 'notification_created', {
          unread_counts: Notification.where(user_id: @comment.run.user.id, read: false).count
        })
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @run = Run.find(params[:run_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to run_path(id: @comment.run_id), notice:"コメントを編集しました"
    else
      render "comments/edit"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.js {render :index}
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:run_id, :content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([run,comment],remote:true) do |f| %>

  <%= f.hidden_field :run_id %>
    <div class="field">
      <p><%= profile_img(current_user) %></p>
      <p><%= f.text_field :content,
             placeholder: "コメントする", class: "form-control input-lg comform" %>
      </p>
    </div>

    <div class="button-panel">
      <%= f.submit "コメントする", class: "button" %>
    </div>
    
<% end %>

app/views/comments/_index.html.erb
<div class="child">
    <% comments.each do |comment| %>
      <% unless comment.id.nil? %>
        <div class="field">
          <p><%= profile_img(comment.user) %></p>
          <p class="color"><strong><%= comment.user.name %></strong></p>
          <p><%= comment.content %></p>
          <% if current_user.id == comment.user.id %>
            <p>
              <%= link_to '', edit_run_comment_path(run, comment), class: "fa fa-commenting fa-lg" %>
              <%= link_to '', run_comment_path(run, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
            </p>
          <% end %>
        </div>
      <% end %>
    <% end %>
</div>

app/views/comments/edit.html.erb
<div class="container-fluid">
  <div class="wrapper col-md-10 col-md-offset-2">
    <div class="title">コメントの編集</div>
    <%= form_for([@run,@comment]) do |f| %>
      <%= f.hidden_field :run_id %>
      <div class="area">
        <%= f.text_area :content , class: "form-control" %>
      </div>
      <div class="button-panel">
        <%= f.submit "コメントを編集する" , class: "button" %>
      </div>
      <%= link_to "記録の詳細へ戻る", run_path(@run.id) , class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</diV>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.run.comments, run: @comment.run }) %>")
$(':text').val('')