config/routes.rb
Rails.application.routes.draw do

  resources :runs do
    resources :comments
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}

  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only:[:index]

  root "top#index"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/run.rb
class Run < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates:addresshyoji,presence: true
  validates:kyori,presence: true
  validates:taikai,presence:true
  validates:time,numericality:{greater_than: 0}
  #validates:hour,numericality: {
  #          only_integer: true ,greater_than_or_equal_to: 0}
  #validates:minute,numericality: {
  #          only_integer: true, greater_than_or_equal_to: 0,
  #          less_than_or_equal_to: 60}
  #validates:second,numericality: {
  #          only_integer: true, greater_than_or_equal_to: 0,
  #          less_than_or_equal_to: 60}
  validates:content,presence:true

  mount_uploader :avatar, AvatarUploader

  geocoded_by :address
  after_validation :geocode, if: Proc.new { |a| a.address_changed? }

  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode,if: Proc.new { |a| a.latitude_changed? or a.longitude_changed? }

end

app/controllers/runs_controller.rb
class RunsController < ApplicationController

before_action :authenticate_user!
before_action :set_run, only: [:show, :edit, :update, :destroy]

  def index
    #ログインユーザーの記録のみ抽出
    @myrun = Run.where(user_id: current_user.id)
    #ソート用のインスタンス設定
    @q= @myrun.ransack(params[:q])
    @run = @q.result(distinct: true)
    set_map
  end

  def new
    @run = Run.new
  end

  def show
    set_map
    @comment = @run.comments.build
    @comments = @run.comments
    Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
  end

  def create
    @run = Run.new(run_params)
    @run.user_id=current_user.id
    @run.name=current_user.name
    set_calc
    if @run.save
      redirect_to runs_path,notice:"大会記録を保存しました"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @run.hour = params[:run][:hour]
    @run.minute = params[:run][:minute]
    @run.second = params[:run][:second]
    @run.kyori = params[:run][:kyori]
    set_calc
    if @run.update(run_params)
      redirect_to runs_path,notice:"大会記録を更新しました"
    else
      render 'edit'
    end
  end

  def destroy
    @run.destroy
    redirect_to runs_path,notice:"大会記録を削除しました"
  end

  private
  def run_params
   params.require(:run).permit(:year,:address,:addresshyoji,:kyori,:taikai,:hour,:minute,:second,:content,:avatar,:latitude,:longitude)
  end

  def set_run
    @run = Run.find(params[:id])
  end

  #GoogleMap表示のデータ
  def set_map
    @hash = Gmaps4rails.build_markers(@run) do |run, marker|
      marker.lat run.latitude
      marker.lng run.longitude
    end
  end

  def set_calc
    #時間、分、秒の設定がなければ「0」を設定
    if @run.hour.nil?
      @run.hour = 0
    end
    if @run.minute.nil?
      @run.minute = 0
    end
    if @run.second.nil?
      @run.second = 0
    end
    #ソート用に記録を秒へ変換
    @run.time = (@run.hour * 3600) + (@run.minute * 60) + (@run.second)
    #記録を表示用に変換
    if @run.hour == 0
      if @run.minute == 0
        @run.timehyoji = @run.second.to_s + '秒'
      else
        @run.timehyoji = @run.minute.to_s + '分' + @run.second.to_s + '秒'
      end
    else
      @run.timehyoji = @run.hour.to_s + '時間' + @run.minute.to_s + '分' + @run.second.to_s + '秒'
    end
    #距離を表示用に変換
    if @run.kyori == 21
      @run.kyorihyoji = 'ハーフ'
    elsif @run.kyori == 42
      @run.kyorihyoji = 'フル'
    else
      @run.kyorihyoji = @run.kyori.to_s + 'km'
    end
  end

end

app/helpers/runs_helper.rb
module RunsHelper

  def run_img(run)
    return image_tag(run.avatar, size:"600x350") if run.avatar.present?
  end

end

app/views/runs/_record_table.html.erb
<!-- 呼び出すコントローラ、アクションによって表示切り替え -->
<% controller_name = controller.controller_name %>
<% action_name = controller.action_name %>

<table>
  <tr>
    <% if (action_name == "index") or (controller_name == "users" and action_name == "show") %>
      <th width="200" height="30"><%= sort_link(q, :year) %></th>
    <% else %>
      <th width="200" height="30">日付</th>
    <% end %>
    <th width="200" height="30">大会</th>
    <th width="200" height="30">場所</th>
    <% if (action_name == "index") or (controller_name == "users" and action_name == "show") %>
      <th width="200" height="30"><%= sort_link(q, :kyori) %></th>
      <th width="200" height="30"><%= sort_link(q, :time) %></th>
    <% else %>
      <th width="200" height="30">距離</th>
      <th width="200" height="30">タイム</th>
    <% end %>
    <th width="200" height="30">編集/削除</th>
  </tr>
    <% if (action_name == "index") or (controller_name == "users" and action_name == "show") %>
      <% @run.each do |run| %>
        <tr>
          <td width="200" height="70"><%= run.year %></td>
          <td width="200" height="70">
            <%= link_to run_path(run) do %>
              <%= run.taikai %>
            <% end %>
          </td>
          <td width="200" height="70"><%= run.addresshyoji %></td>
          <td width="200" height="70"><%= run.kyorihyoji %></td>
          <td width="200" height="70"><%= run.timehyoji %></td>
          <td width="200" height="70">
            <% if run.user_id == current_user.id %>
              <div class="button-inline">
                <%= link_to "編集", edit_run_path(run), class: "btn btn-primary btn-block" %>
                <%= link_to "削除", run_path(run), method: :delete,data:{confirm:'削除してもいいですか？？'}, class:"btn btn-primary btn-block" %>
              </div>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td width="200" height="70"><%= run.year %></td>
        <td width="200" height="70"><%= run.taikai %></td>
        <td width="200" height="70"><%= run.addresshyoji %></td>
        <td width="200" height="70"><%= run.kyorihyoji %></td>
        <td width="200" height="70"><%= run.timehyoji %></td>
        <td width="200" height="70">
          <% if run.user_id == current_user.id %>
            <div class="button-inline">
              <%= link_to "編集", edit_run_path(run), class: "btn btn-primary btn-block" %>
              <%= link_to "削除", run_path(run), method: :delete,data:{confirm:'削除してもいいですか？？'}, class:"btn btn-primary btn-block" %>
            </div>
          <% end %>
        </td>
      </tr>
    <% end %>
</table>

app/views/runs/_runform.html.erb
<%= form_for(run) do |f| %>

  <% if @run.errors.any? %>
    <div id="errors">
      <h2><%= @run.errors.count %>件のエラーがあります。</h2>
      <ul>
        <%= @run.errors.full_messages.each do |msg| %>
          <li><% msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="title">〜大会記録を保存しよう〜</div>
  <div class="field"><h4><%= f.label :大会の開催日を設定しよう %></h4></div>

  <%= raw sprintf(
      f.date_select(
       :year,
       {start_year: Time.now.year - 1,
       end_year: Time.now.year,
       order: [ :year, :month, :day ],
       use_month_numbers: true,
       date_separator:    '%s'},
       {class: "form-control input-lg bootstrap-dt"}),
       '年 ', '月 ') + '日' %>

  <div class="field"><h4><%= f.label :開催地を設定しよう %></h4></div>

  <%= f.text_field :addresshyoji,id:"addresshyoji",onchange: "getaddress()",
      placeholder: "【都道府県市区町村 or スタート地点】 を入力してください",
      class: "form-control input-lg bootstrap-place" %>

  <%= f.hidden_field :address, id: "address" %>

  <div class="field"><h4><%= f.label :種目を設定しよう %></h4></div>
  <%= f.select :kyori,
        [["5km","5"],["10km","10"],["ハーフ","21"],
        ["30km","30"],["フル","42"],["100km","100"]],
        {prompt: "走った距離を選択してください"},
        class: "form-control input-lg" %>

  <div class="field"><h4><%= f.label :大会名を設定しよう  %></h4></div>
  <%= f.text_field :taikai, class: "form-control  input-lg" %>

  <div class="field"><h4><%= f.label :タイムを設定しよう  %></h4></div>
  <%= f.number_field :hour, class: "form-control input-lg bootstrap-dt",
      placeholder: "時間", min:0 %>時間
  <%= f.number_field :minute, class: "form-control input-lg bootstrap-dt",
      placeholder: "分",min: 0 ,max: 60 %>分
  <%= f.number_field :second, class: "form-control input-lg bootstrap-dt",
      placeholder: "秒",min: 0 ,max: 60 %>秒

  <div class="field"><h4><%= f.label :大会の思い出を記録しよう %></h4></div>
  <div class="area">
    <%= f.text_area :content,rows: "5" , class: "form-control input-lg" %>
  </div>

  <div class="field"><h4><%= f.label :思い出の写真を投稿しよう %></h4></div>
  <%= run_img(run) if run_img(run) %>
  <%= f.file_field :avatar %>
  <%= f.hidden_field :avatar_cache %>

  <div class="button-panel">
    <%= f.submit "大会記録を登録する", class: "button"%>
  </div>
  <%= link_to "大会記録一覧へ戻る", runs_path, class: "btn btn-primary btn-block"  %>
<% end %>

app/views/runs/edit.html.erb
<div class="container-fluid">
  <div class="wrapper col-md-10 col-md-offset-2">
    <%= render partial: 'runform', locals:{run: @run} %>
  </div>
</div>

app/views/runs/index.html.erb
<div class="container-fluid">
  <div class="wrapper col-md-10 col-md-offset-2">
    <%= notice %>
    <!-- ログインユーザーの大会記録一覧表示-->
    <div class="title">〜<%= current_user.name %>の大会記録一覧〜</div>
    <div class="field"><h5>※日付・距離・タイムのタイトルをクリックすると、それぞれ昇順/降順に並び替えできます。</h5></div>
    <%= render partial: 'record_table', locals:{ q: @q, run: @run } %>

    <% unless @run.empty? %>
      <div id="map"></div>
      <script type="text/javascript">
        handler = Gmaps.build('Google');
        handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
          markers = handler.addMarkers(<%=raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          handler.getMap().setZoom(5);
        });
      </script>
    <% end %>

  </div>
</div>

app/views/runs/new.html.erb
<div class="container-fluid">
  <div class="wrapper col-md-10 col-md-offset-2">
    <%= notice %>
    <%= render partial: 'runform', locals:{ run: @run } %>
  </div>
</div>

app/views/runs/show.html.erb
<div class="container-fluid">
  <div class="wrapper col-md-10 col-md-offset-2">
    <%= notice %>
    <div class="title">〜記録の詳細〜</div>
    <div class="right"><strong>作成日時:</strong><%= @run.created_at.strftime("%y/%m/%d %p %I:%M") %></div>
    <%= render partial: 'record_table', locals:{ run: @run } %>

    <p><%= run_img(@run) if run_img(@run) %></p>

    <div id="map"></div>
    <script type="text/javascript">
      handler = Gmaps.build('Google');
      handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        handler.getMap().setZoom(15);
      });
    </script>

    <div id="comments_area">
      <%= render partial:'comments/index',locals:{comments:@comments,run:@run}%>
    </div>
    <% if @run.user_id != current_user.id %>
      <%= render partial:'comments/form',locals:{comment:@comment,run:@run} %>
    <% end %>
    <!--<div class="link">
      <%= link_to "大会記録一覧へ", runs_path(@run), class: "btn btn-primary btn-block" %>
      <%= link_to "ユーザー詳細一覧へ", user_path(@run), class: "btn btn-primary btn-block" %>
    </div>-->
  </div>
</div>