config/routes.rb
Rails.application.routes.draw do

  resources :runs do
    resources :comments
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}

  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only:[:index]

  root "top#index"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>どこ走った？？</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta charset="utf-8">
  <script src="https://maps.google.com/maps/api/js?key=<%= ENV["GOOGLE_MAP"]%>" charset="utf-8"></script>
  <script src='https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <script src="https://cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"</script>
  <script src='https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'</script>
  <script src="https://js.pusher.com/4.1/pusher.min.js"></script>

  <!-- GoogleMap表示領域の設定-->
  <style>
    #map {
          height: 500px;
          width: 100%;
         }
  </style>

  <% if user_signed_in? %>
    <script>
      var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>',{
        encrypted: true,
        cluster: 'ap1'
      });

      var channel = pusher.subscribe("user_<%= current_user.id %>_channel");
      channel.bind('comment_created', function(data) {
        alert(data.message);
      });
      channel.bind('notification_created', function(data) {
        $('#unread_count').html(data.unread_counts);
      });
    </script>
  <% end %>

</head>

<body>
  <div id="fh5co-page">
  	<aside id="fh5co-aside" role="complementary" class="border js-fullheight">
      <nav id="fh5co-main-menu" role="navigation">
  		  <ul>
          <span class="under">
  					<li><%= link_to "ホーム",root_path %></li>
  					<li><%= link_to "どこ走った？？", new_run_path %></li>
  					<li><%= link_to "ここ走ったよ", runs_path %></li>
  					<li><%= link_to "ユーザー一覧", users_path %></li>
              <% if user_signed_in? %>
                <li><%= link_to "マイメニュー", edit_user_registration_path %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path,method: :delete %></li>
              <% else %>
                <li><%= link_to "ログイン", new_user_session_path %></li>
              <% end %>
          </span>
  			</ul>
  		</nav>

      <% if user_signed_in? %>
        <%= link_to notifications_path, class: "navbar-brand" do %>
          <i class="fa fa-hand-stop-o"><span id="unread_count">未読コメント<%= @notifications_count %>件</span></i>
        <% end %>
      <% end %>

  		<div class="fh5co-footer">
  			<small>&copy; 2017 Keita Morita</small>
  		</div>

  	</aside>
  </div>

  <%= yield %>

  </body>
</html>